### ISSUE TITLE
Spinner keeps spinning

### ISSUE THREAD

**Issue by Nilhan2022** [mehmetcanfarsak/FormToEmailService#1]
Hi, Ive deployed as you said and added a form in my website.
But I get the spinning forever.., after captcha filled correctly, In deta base message is present.. but I didn't get the email

**Comment by mehmetcanfarsak** [comment]
hi
Let me Check I will get back to you ASAP

**Comment by mehmetcanfarsak** [comment]
Hi,
I have found the bug you had trouble.

Also I have made some performance improvements. 😃 
 Form submission is now faster.
Can you re-deploy, it should work now?
